### ISSUE TITLE
Wrapping the query builder object instead of query().finder

### ISSUE THREAD

**Issue by koskimas** [snlamm/objection-dynamic-finder#1]
Hi,

First of all, an awesome idea for a plugin! Great to see `Proxy` in use.

Have you considered wrapping the actual query builder with a proxy instead of exposing a `finder` getter? This probably isn't obvious from the docs, but the `Model.query()` method is always used to create an instance of a query builder. Therefore you could do something like this:

```js
return class extends Model {
  static query(...args) {
    const qb = super.query(...args);
    return new Proxy(qb, handler);
  }
}
```

**Comment by koskimas** [comment]
Here's a standalone example of what I mean:

```js
const Model = require('objection').Model;
const knex = require('knex')({
  client: 'sqlite3',
  useNullAsDefault: true,
  connection: {
    filename: ':memory:'
  }
});

const Finder = Model => class extends Model {
  static query(...args) {
    const qb = super.query(...args);

    return new Proxy(qb, {
      get(target, propKey) {
        if (propKey in target) {
          return target[propKey];
        } else {
          return (...args) => {
            // Do your thing here.
            console.log(propKey, ...args);
            return qb;
          };
        }
      }
    });
  }
}

class Person extends Finder(Model) {
  static get tableName() {
    return 'Person';
  }
}

async function createDb() {
  return knex.schema.createTable('Person', table => {
    table.increments('id').primary();
    table.string('name');
  });
}

async function insertData() {
  return Person.query(knex).insertGraph([{
    name: 'Jennifer'
  }, {
    name: 'Brad'
  }]);
}

async function start() {
  await createDb();
  await insertData();

  const jennifer = await Person.query(knex).findOne({name: 'Jennifer'});
  console.log(jennifer);

  Person.query(knex).firstNameAndLastName('Foo', 'Bar');
}

start().then(() => knex.destroy()).catch(err => {
  console.error(err.stack);
  return knex.destroy();
});
```

**Comment by snlamm** [comment]
Thanks! I’m a huge fan of Objection, btw.
Wrapping query() is a good idea. I’m going to build it out and see how it goes.

I think it's worth it to scrap `.finder`, though it'll have ripple effects on error handling: 
1. Losing the 'Querying invalid field' error that came with `.finder`. For example: without `.finder`, `Person.query().whhere(‘foo’)` and `Person.query().ffirstName(‘foo’)` will have to be handled the same way even though one is a failed attempt to use QueryBuilder's `where()` and the other is a failed attempt to use `where('non-existing-field')`. 

2. Using jsonSchemas for validation will have to be mandatory rather than merely a good idea. Otherwise `Person.query().wwhere('foo')` will turn into `Person.query().where('wwhere', 'foo')`.

3. I'd like to preserve the current behavior that `Person.query().wwhere === undefined`. So to build on point 1 above, the error returned for both examples there will probably end up being a standard `TypeError 'X is not a function'`

**Comment by koskimas** [comment]
Very good points! I didn't think of those. I have no preference over this. I just found this plugin super interesting and wondered if you had thought of this. Feel free to just close this if you want 😄

**Comment by snlamm** [comment]
I appreciate the input! I took a [first pass](https://github.com/snlamm/objection-dynamic-finder/compare/wrap-query-builder) at a refactor and it works, though I'll need to clean it up a bit. For now I'll close this and keep things the same, with the potential to revisit : )
